### ISSUE TITLE
tests fail with system(wait = FALSE) with R 3.6 on Windows

### ISSUE THREAD

**Issue by mem48** [r-lib/testthat#1272]
I have a function in my package that starts an external program using `system("my commands", intern = FALSE, wait = FALSE)`. 

This has been working for a long time, and my tests of this function also work. But recently my tests have started running indefinitely and I have narrowed down the problem to the fact that `testthat` does not seem to be honouring the `wait = FALSE` instruction. This only appears to occur on R 3.6 on Windows, and as the problem has only started recently I assume it is in some way related to the latest version of `testthat`.

I've tried to produce a simpler reproducible example:

```
# Simple function that will make a system call to Windows command line and then do nothing
# If wait = TRUE, function should take about 4 seconds to run
# If wait = FALSE, functon should return immediately
sleep_test <- function(wait){
  r <- system("ping -n 5 127.0.0.1", intern = wait, wait = wait)
  return(TRUE)
}


test_that("Does not wait", {
  t1 <- Sys.time()
  t <- system.time(sleep_test(FALSE))
  t2 <- Sys.time()
  expect_true(t[[3]] < 1)
  expect_true(as.numeric(difftime(t2,t1)) < 1)
})

test_that("Does wait", {
  t1 <- Sys.time()
  t <- system.time(sleep_test(TRUE))
  t2 <- Sys.time()
  expect_true(t[[3]] > 4)
  expect_true(as.numeric(difftime(t2,t1)) > 4)
})

```
These tests run without any problem if I simply run the script. But if I put them into a package structure and use `devtools::check()` or the `Run Tests` button in RStudio then the tests for "Does not wait" will fail.

Intrestingly the test `expect_true(t[[3]] < 1)` passes but the test `expect_true(as.numeric(difftime(t2,t1)) < 1)` fails.

In my actual use case, I end up with the tests running indefinitely because my `system()` call starts a program. The program is waiting for further instructions from R and R is waiting for the program to finish. Thus both wait forever.

**Comment by hadley** [comment]
It's not obvious to me how testthat might have changed to affect this, but in general we stay away from `system()` because of problems exactly like this. You might try using processx instead.

**Comment by gaborcsardi** [comment]
AFAIR on Windows `R CMD check` hangs if you don't clean up your background processes at the end of the tests, at least it used to.

**Comment by hadley** [comment]
Ok, given that I think @mem48 definitely needs a different approach.

**Comment by mem48** [comment]
@gaborcsardi In my actually tests I do, this problem happens midway through the tests.

Also, I have confirmed the problem does not exist with `testthat` 2.3.2

**Comment by gaborcsardi** [comment]
@mem48 Can you create a minimal package that has this problem?

**Comment by mem48** [comment]
Yes https://github.com/ITSLeeds/brokenPackage

**Comment by mem48** [comment]
Sorry, I committed the tests and then forgot to push

**Comment by mem48** [comment]
I've made a minimal example of exactly what I'm trying to do in the example package and I can get the error to occur on GitHub actions https://github.com/ITSLeeds/brokenPackage/actions/runs/413893357 only this time it ran fine on R 3.6 but failed on R 4.0. But still no problems on other OS.

**Comment by gaborcsardi** [comment]
Here is my fork: https://github.com/gaborcsardi/brokenPackage

I removed most dependencies, and also removed testthat. `rcmdcheck::rcmdcheck()` still fails, `R CMD check` sometimes fails as well.

So this has not much to do with testthat it seems. You cannot keep background processes running, you need to clean them up before the end of the test file. This is not trivial at all, especially if your background processes start subprocesses.

**Comment by mem48** [comment]
Thanks @gaborcsardi at least that helps me work out what the problem is.
