### ISSUE TITLE
isolating terminal width in expect_snapshot()?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/testthat#1567]
I have started seeing a few test failures internally along the lines of:

```
── Failure (test-filter.r:387:3): filter() gives useful error messages ───────────────────────────
Snapshot of code has changed:
     old                                                                                  | new                                                                               
[19] "Output"                                                                             | "Output"                                                                      [19]
[20] "  <error/rlang_error>"                                                              | "  <error/rlang_error>"                                                       [20]
[21] "  Error in `filter()`:"                                                             | "  Error in `filter()`:"                                                      [21]
[22] "  ! Problem while computing `..1 = matrix(c(TRUE, FALSE, TRUE, FALSE), nrow = 2)`." - "  ! Problem while computing `..1 = matrix(c(TRUE, FALSE, TRUE, FALSE), nrow" [22]
                                                                                          - "    = 2)`."                                                                  [23]
[23] "  x Input `..1` must be a logical vector, not a logical[,2]."                       | "  x Input `..1` must be a logical vector, not a logical[,2]."                [24]
[24] "Code"                                                                               | "Code"                                                                        [25]
[25] "  (expect_error(iris %>% group_by(Species) %>% filter(c(TRUE, FALSE))))"            | "  (expect_error(iris %>% group_by(Species) %>% filter(c(TRUE, FALSE))))"     [26]
```

Noting that:

```
nchar("  ! Problem while computing `..1 = matrix(c(TRUE, FALSE, TRUE, FALSE), nrow = 2)`.")
# [1] 82
```

it looks like somehow the environment producing the snaps and the one running our tests have divergent terminal widths.

Is there a way to ensure the terminal width is fixed within the code generating snapshots to prevent this sort of discrepancy?

**Comment by gaborcsardi** [comment]
The terminal width is fixed in the third edition by calling `testthat::local_reproducible_output()` automatically. If you are using the second edition, then you'll need to call it, or something similar, at the beginning of the `test_that()` block.

**Comment by MichaelChirico** [comment]
Hmm I am still seeing this, but it must be something internal for us. I'll re-open if I can pinpoint the issue better. Thanks for pointing to `local_reproducible_output()`, that will help in debugging.
